// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTD8U1QXWx3dI3nsSSljf4ojR3iH0aV2E',
    appId: '1:1092871271771:web:657b83621a654a46a7567e',
    messagingSenderId: '1092871271771',
    projectId: 'omniai-c0f6c',
    authDomain: 'omniai-c0f6c.firebaseapp.com',
    storageBucket: 'omniai-c0f6c.firebasestorage.app',
    measurementId: 'G-6RCKWH9MWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtxhqyPZa-FL-N7Hf8tpNEHOx6xV-2YYI',
    appId: '1:1092871271771:android:5147c412504efafea7567e',
    messagingSenderId: '1092871271771',
    projectId: 'omniai-c0f6c',
    storageBucket: 'omniai-c0f6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEDlREmc51kaYKrv4kVlIVTOWULzrPANE',
    appId: '1:1092871271771:ios:b01b535caca2071aa7567e',
    messagingSenderId: '1092871271771',
    projectId: 'omniai-c0f6c',
    storageBucket: 'omniai-c0f6c.firebasestorage.app',
    iosBundleId: 'com.omniai.omniai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEDlREmc51kaYKrv4kVlIVTOWULzrPANE',
    appId: '1:1092871271771:ios:b01b535caca2071aa7567e',
    messagingSenderId: '1092871271771',
    projectId: 'omniai-c0f6c',
    storageBucket: 'omniai-c0f6c.firebasestorage.app',
    iosBundleId: 'com.omniai.omniai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTD8U1QXWx3dI3nsSSljf4ojR3iH0aV2E',
    appId: '1:1092871271771:web:1cb06ae11c3d43b4a7567e',
    messagingSenderId: '1092871271771',
    projectId: 'omniai-c0f6c',
    authDomain: 'omniai-c0f6c.firebaseapp.com',
    storageBucket: 'omniai-c0f6c.firebasestorage.app',
    measurementId: 'G-6Q4CSB8TJF',
  );
}
